apiVersion: skaffold/v2beta13
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
    flags:
      global: # additional flags passed on every command.
      - --namespace=hooli-poc
build:
  local:
    push: false
  artifacts:
    - image: davybello/sgauth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
