apiVersion: apps/v1
kind: Deployment
metadata:
  name: fusion-mysql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fusion-mysql
  template:
    metadata:
      labels:
        app: fusion-mysql
    spec:
      containers:
        - name: fusion-mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql"
              name: mysql-data
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: fusionauth-mysql-data-disk
---
apiVersion: v1
kind: Service
metadata:
  name: fusion-mysql-srv
spec:
  selector:
    app: fusion-mysql
  ports:
    - name: db
      protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fusionauth-mysql-data-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi